---
output: 
  html_document:
    theme:
      base_font: bslib::font_google("Open Sans")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

source('R/rscpages2.R')
```

```{r get-content, echo=FALSE, message=FALSE, warning=FALSE}
library(connectapi)
library(dplyr)
library(bslib)

# setup connect client
rsc <- connect()

# get tags from RSC
tags <- get_tag_data(rsc)

# pull tag id by name
project_tag <- "Dashboards"
project_tag_id <- tags %>% 
  filter(name == project_tag) %>% 
  pull(id)

# get content based on the tag of interest
# other pre-call filters work too, e.g.
# list(name="content name")
# but this relies on the internal API spec not the /v1/content API
content <- get_content(rsc, filter = list(tag=project_tag_id))

# post API filters could be applied here as well
content <- content %>% 
  filter(title != "test-app")

# get images for content
content <- content %>% 
  rowwise() %>% 
  mutate(image = rsc_save_image(rsc, guid, "logo.png"))
```

```{r build-page}
rsc_project_page()
rsc_navbar('./logo.png')
rsc_project_info(project_tag, "Info about my awesome project")
rsc_tiles(content)
```

